[tool.taskipy.tasks]
installed-packages = { cmd = "pip list", help = "Lista pacotes Python instalados." }
convert-csv = { cmd = "python scripts/convert_csv.py", help = "Converte arquivos Excel em csv." }
datapackage-yaml = { cmd = "python scripts/create_datapackage_yaml.py", help = "Converte cria datapackage.yaml caso este ainda não exista." }
