[tool.taskipy.tasks]
installed-packages = { cmd = "pip list", help = "Lista pacotes Python instalados." }
convert-csv = { cmd = "python scripts/convert_csv.py", help = "Converte arquivos Excel em csv." }
