[tool.taskipy.tasks]
linux-env = { cmd = "python3 -m venv venv", help = "Cria ambiente virtual python em m치quina linux." }
windows-env = { cmd = "python -m venv venv", help = "Cria ambiente virtual python em m치quina windows." }
linux-install = { cmd = "source venv/bin/activate && pip install -r requirements.txt", help = "Instala pacotes python em m치quina linux." }
windows-install = { cmd = "source venv/Scripts/activate && pip install -r requirements.txt", help = "Instala pacotes python em m치quina linux." }
list = { cmd = "pip list", help = "Lista pacotes Python instalados." }
