[tool.taskipy.tasks]
installed-packages = { cmd = "pip list", help = "Lista pacotes Python instalados." }
convert_csv = { cmd = "python scripts/convert_csv", help = "Converte arquivos Excel em csv." }
