name: Validação Frictionless

on:
  workflow_run:
    workflows: ["publish_update"]

jobs:
  frictionless_validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Frictionless validate
        uses: frictionlessdata/repository@v2
