name: Publicação/atualização de dataset em instância CKAN

on:
  push:
    paths:
      - 'dataset/*'
      - 'upload/*'

jobs:
  publish_update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install packages
        run: pip install -r requirements.txt
      - name: Convert CSV
        run: task csv
      - name: Commit CSV
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Converte Excel para CSV via script.
      - name: Create datapackage.yaml
        env:
          DATASET_NAME: ${{ github.event.repository.name }}
          OWNER_ORG: ${{ secrets.OWNER_ORG }}
        run: task yaml
      - name: Commit new datapackage.yaml
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Cria datapackage.yaml caso não exista via script.
      - name: Create datapackage.json
        run: task json
      - name: Commit new datapackage.json
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Cria datapackage.json via script.
      - id: string
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ github.actor }}
      - name: Create dataset in CKAN with not exist
        env:
          CKAN_HOST: ${{ secrets.CKAN_HOST }}
          CKAN_KEY: ${{ secrets[format('CKAN_KEY_{0}', steps.string.outputs.uppercase)] }}
        run: dpckan --datastore --datapackage dataset/datapackage.json --ckan-host "$CKAN_HOST" --ckan-key "$CKAN_KEY" dataset create
      - name: Update dataset in CKAN with dpckan with exist
        env:
          CKAN_HOST: ${{ secrets.CKAN_HOST }}
          CKAN_KEY: ${{ secrets[format('CKAN_KEY_{0}', steps.string.outputs.uppercase)] }}
        run: dpckan --datastore --datapackage dataset/datapackage.json --ckan-host "$CKAN_HOST" --ckan-key "$CKAN_KEY" dataset update
